tiagopog/jsonapi-utils

lib/jsonapi/utils.rb
`JSONAPI::Resources` by default [configures the default paginator to `:none`](https://github.com/cerebris/jsonapi-resources#configuration), but `config.top_level_links_include_pagination = true`. 
Doesn't seem to make sense to me to try and paginate based on whether someone wants top level links to include pagination, but rather based on whether there's any paginator configured.
Thanks! 😄
=> Only paginate collection results if paginator is specified

lib/jsonapi/utils.rb
From: https://github.com/plataformatec/devise/pull/3732
> Currently Devise::Controllers::Helpers depends on #helper_method, which is defined inside AbstractController::Helpers. This module is included in ActionController::Base, but it is not included by default in ActionController::Metal.
> #helper_method is not essential to the functionality of the methods inside Devise::Controllers::Helpers, so this PR wraps all Devise #helper_method calls with respond_to?(:helper_method) checks.
This console output elucidates the issue:
```ruby
[14] pry(main)> ActionController::Base.ancestors.map(&:to_s).grep(/Helpers/)
=> ["ActionDispatch::Routing::RouteSet::MountedHelpers", "ActionController::Helpers", "AbstractController::Helpers"]
[15] pry(main)> …
```
=> Don't try to add jsonapi_serialize as helper unless it's possible to do so

jsonapi-utils.gemspec
Introducing `git` as a dependency in the `<gem-name>.gemspec` file introduces a problem for those of us isolating our applications within Docker containers that don't otherwise need `git`.
=> Don't add git dep in gemspec

jsonapi-utils.gemspec, lib/jsonapi/utils.rb, lib/jsonapi/utils/version.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb, spec/support/controllers.rb, spec/support/exceptions.rb, spec/support/models.rb, spec/support/shared/jsonapi_request.rb
Fixes #12 
Due to a change on how `JSONAPI::Resources` deals with the setup and check of requests around its operations, the methods `JSONAPI::Utils#(setup_request|json_api_(render|serialize))` had to change as well, since the request validation and error rendering that once were handled by `JR` now needed to be handled by `JU`.
Unfortunately the implementation caused a bug when dealing with invalid requests:
1. An invalid request is made (e.g. an invalid param);
2. Resource is persisted with no errors, since its validation has passed;
3. When it tries to render the response then an error message is rendered showing the issues with the invalid param. 
Now it sets up and checks the request before the action executes. This makes much more sense than validating the request after the actual …
=> Setup and check request before action executes

.travis.yml, README.md, jsonapi-utils.gemspec, lib/jsonapi/utils/version.rb
The goal of these commits is to add support for [jsonapi-resources v0.8.0.beta2](https://github.com/cerebris/jsonapi-resources/tree/v0.8.0.beta2).
This includes:
* Updating the runtime dependency version
* Bumping this gem a beta version
* Updating the README
=> Update jsonapi-resources runtime version to 0.8.0.beta2

README.md, jsonapi-utils.gemspec, lib/jsonapi/utils.rb, lib/jsonapi/utils/response/formatters.rb
Closes #33 (see the issue for additional discussion)
This PR:
* Removes the runtime dependency for piped_ruby, and simply reverts the piped ruby code back to its original.
* Updates JSONAPI::Resources to 0.8.0 (final)
* Fixes some readme spelling errors and broken links
Regarding piped ruby, I agree with @tiagopog that the reverted section (where piped ruby was implemented) is somewhat ugly and could/should be refactored, but I don't think we should introduce an unneeded dependency between the beta and final version.  Let's get it up to a full release using the new release of JSONAPI::Resources and then look at options for refactoring that method.
Additionally, I do not have code in this PR that changes version of the gem, as I don't know what your versioning/PR process is.  Please feel …
=> Updates JSONAPI::Resources to 0.8.0; Removes piped_ruby dependency

README.md, lib/jsonapi/utils/support/pagination.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb, spec/support/paginators.rb, spec/support/shared/jsonapi_errors.rb
This is a proposed fix for: #30 
* Global paginators can be configured with
`JSONAPI.configuration.default_paginator = :your_custom_paginator`
* Custom Paginator ranges for hashes are delegated to
Paginator#paginaton_range
Notes:
* I noticed that resource specific paginators don't have any tests except for the shared examples. I can add them if desired.
* If this fix is on the right track, I can update the README with some documentation on how to have to implement the `pagination_range` method for custom paginators.
=> Add support for custom paginators

lib/jsonapi/utils/support/pagination.rb
* The following error occurs when using this gem with Rails 5
DEPRECATION WARNING: Method with_indifferent_access is deprecated and
will be removed in Rails 5.1, as `ActionController::Parameters` no
longer inherits from hash.
To fix this issue, let's permit all the attributes then pull out the
page parameters. Note that all attributes need to be permitted due
to strong parameters not allowing attributes to be dynamically
permitted.
=> Permit page parameters to remove Rails 5 deprecation warning

lib/jsonapi/utils/support/filter/default.rb, lib/jsonapi/utils/support/sort.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/users_controller_spec.rb
Fixes #39 
There's a bug related to the use of keys other than `:underscored_key` for filter and sort operations.
This PR fixes the above mentioned issue taking advantage of the method `JSONAPI::RequestParser#unformat_key` which converts keys from any format to the standard `:underscored_key` format.
=> Unformat keys for filter and sort operations.

lib/jsonapi/utils/exceptions.rb, lib/jsonapi/utils/response/formatters.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb, spec/support/controllers.rb, spec/support/factories.rb, spec/support/models.rb, spec/support/resources.rb
Closes #38 
-  Handles attributes vs. base vs. relationships in pointer - `/data/attributes/title` vs. `/data` vs.
`/data/relationships/category`, respectively
-  Smart enough to convert a foreign-key-based validation to the association name - `category_id`
becomes `category` after reflecting on `belongs_to` associations
-  Needed to move some test stuff around:
-  Example of rendering for array of hashes moved from PostsController to UsersController
-  Added contrived base error to UsersController#update
-  Added Category model for testing foreign-key error key (`category_id`)
Of course, I am open to criticisms, suggestions for refactoring, etc.
=> Add source.pointer error object for ActiveRecord

lib/jsonapi/utils/response/formatters.rb, spec/controllers/profile_controller_spec.rb, spec/spec_helper.rb, spec/support/controllers.rb, spec/support/models.rb, spec/support/resources.rb
I have a model in my application that includes `ActiveModel::Model` instead of extending `ActiveRecord::Base`, so I had to make a slight modification to the error formatter in JU to allow for it.
In case you're not familiar with this pattern... Though this [ActiveModel Form Objects example](https://robots.thoughtbot.com/activemodel-form-objects) isn't for an API, hopefully you can see its value in creating models not backed by a specific database table.
The controller specs I setup are basically there to make sure that the renderers don't choke on one of these special resource, not really to test much else functionality other than that.
=> Add support for classes that include ActiveModel::Model

jsonapi-utils.gemspec, lib/jsonapi/utils/request.rb, lib/jsonapi/utils/version.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb, spec/support/factories.rb, spec/support/models.rb, spec/support/resources.rb
This PR fixes a buggy behavior from `jsonapi-resources`, for one-to-one relationships, reported in #53.
=> Update jsonapi-resources to 0.8.0

README.md, jsonapi-utils.gemspec, lib/jsonapi/utils/version.rb, spec/controllers/posts_controller_spec.rb, spec/controllers/profile_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/spec_helper.rb, spec/support/factories.rb, spec/support/models.rb, spec/support/resources.rb, spec/support/shared/jsonapi_errors.rb
Just a patch to update `jsonapi-resources` to [`v0.8.3`](https://github.com/cerebris/jsonapi-resources/releases/tag/v0.8.3).
=> Update jsonapi-resources to v0.8.3

jsonapi-utils.gemspec, lib/jsonapi/utils/request.rb, spec/support/resources.rb
Gets tests passing by fixing changes to process operations, and the new foreign_key_on option.
=> First pass at supporting jsonapi-resource 0.9

lib/jsonapi/utils/response/formatters.rb
if ActiveRecord is not loaded in your project, but the method `jsonapi_render_errors` is called, the code tries to see if the object passed in is an active record object or not.  But in doing so, it assumed active record is loaded to make said comparison.
If active record is not loaded, now the `active_record_obj?` method in `JSONAPI::Utils::Response::Formatters` always fails, which is good.
=> eliminate ActiveRecord as a dependency for errors

lib/jsonapi/utils/support/sort.rb
This pull requests fixes an incompatibility with the **globalize** gem [https://github.com/globalize/globalize](url). The gem is used to translate fields of models stored in a database using a translation table for these fields. Most **ActiveRecord** methods are extended to automatically join the translation table and replace the regular field names with the fields from the translation table.
However, the `order` method was not working with the parameters supplied by **jsonapi-utils** because Symbols were expected as keys in the sort parameter hash and not Strings. I added a conversion to the `sort_params` method. This fix should not interfere with the default **ActiveRecord** behavior as it works with both Strings and Symbols.
=> Fix for incompatibility with "globalize" gem

lib/jsonapi/utils/response/formatters.rb
Pagination and sorting was not working as expected for Arrays.
Expected behavior: Result is sorted by specified attributes and then paged
Current behavior: The result set was first paged and then the page was sorted by the specified attributes.
This is no issue for ActiveRecord::Collections as .order(), .offset(), and .limit() can be called in any order with the same result.
=> Sort and pagination was applied in wrong order for Arrays

jsonapi-utils.gemspec, lib/jsonapi/utils/request.rb, spec/controllers/posts_controller_spec.rb
Tests are passing.
So far it seems like the only breaking change was this: https://github.com/cerebris/jsonapi-resources/commit/970bc7922bc162fb36cb5e67f511a8b63b45024f
Closes #93
=> Compatibility with jsonapi-resources@0.9.7

jsonapi-utils.gemspec, spec/controllers/users_controller_spec.rb
Previous upgrade was in #98 
Spec change reflects new JR behavior of not including relationship links in case its routes were not defined:
https://github.com/tiagopog/jsonapi-utils/blob/36c76019472b692295172a7945f40c8da9d85441/spec/test_app.rb#L61-L64
It does not call `jsonapi_related_resource :profile` within the block.
=> Compatibility with jsonapi-resources@0.9.9

README.md
There is no need to add _paginator in pagination config- paginator_klass do this already:
def paginator_klass
"#{JSONAPI.configuration.default_paginator}_paginator".classify.constantize
end
=> Remove redundant _paginator from docs example
